EX_ID = ex1

NODES = 2

MONGODB_ADDRESS_TYPE = ip
MONGODB_ADDRESS = 192.168.1.100
# MONGODB_ADDRESS_TYPE = domain
# MONGODB_ADDRESS = mongodb-service.com

MONGODB_USERNAME = admin5
MONGODB_PASSWORD = password5
