apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: {{ .Values.secrets.mongoRootUsername | b64enc }}
  mongo-root-password: {{ .Values.secrets.mongoRootPassword | b64enc }}
